project:
  type: website
  output-dir: docs

website:
  title: "Analytici 2022"
  page-footer: "Petr Bouchal pro Ministerstvo vnitra, 2023"
  repo-url: https://github.com/petrbouchal/msmt
  repo-actions: [edit, issue]
  page-navigation: true
  search:
    location: navbar
    type: textbox
  navbar:
    background: blue
    left:
      - href: index.qmd
        text: Start
      - href: slides/index.qmd
        text: Prezentace
      - href: report.qmd
        text: Příklad analýzy v R
      - zdroje.qmd
    right:
      - icon: github
        href: https://github.com/petrbouchal/msmt
      - icon: asterisk
        href: https://petrbouchal.xyz
      - text: " "

format:
  html:
    toc: true
    html-math-method: plain
    theme:
      light: [default, style.scss]
    monobackgroundcolor: "#e3f1ff"
    mainfont: "IBM Plex Sans, Helvetica, Arial, sans-serif"
    monofont: "JetBrainsMono Nerd Font, JetBrains Mono, IBM Plex Mono, Consolas, monospace"
    max-width: 1200px
    lang: cs
    link-external-newwindow: true
    fig-cap-location: margin
    tab-cap-location: margin
    footnotes-hover: true
    reference-location: margin

filters:
  - pandoc-quotes.lua
execute:
  echo: false
  warning: false
knitr:
  opts_chunk:
    comment: "#>"
    dev: "ragg_png"
    message: false
    fig.retina: 3
    # out.width: "100%"
editor: source

