project:
  type: website

website:
  title: "analytici"
  navbar:
    left:
      - href: index.qmd
        text: Start
      - href: slides/index.qmd
        text: Prezentace
      - href: report.qml
        text: Příklad analýzy v R
      - zdroje.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

