project:
  type: website
  output-dir: docs

website:
  title: "Analytici 2022"
  navbar:
    left:
      - href: index.qmd
        text: Start
      - href: slides/index.qmd
        text: Prezentace
      - href: report.qmd
        text: Příklad analýzy v R
      - zdroje.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

